<a href="https://colab.research.google.com/github/cpernot/Learn_pytorch/blob/main/00_pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
print ("hello")


hello


In [56]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [57]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.5.1+cu121


In [58]:
## Introduction to Tensors

In [59]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [60]:
scalar.ndim

0

In [61]:
scalar.item()

7

In [62]:
MATRIX = torch.tensor([[1,1],[2,2]])
print(MATRIX.ndim)
print(MATRIX.shape)
TENSOR =torch.tensor([[[1,2,3,4],[2,2,2,2],[3,3,3,3]],
                      [[1,2,3,4],[2,2,2,2],[3,3,3,3]]])
print(TENSOR.ndim)
print(TENSOR.shape)

2
torch.Size([2, 2])
3
torch.Size([2, 3, 4])


###Random Tensors

## #Create a random tensor of size (3,4)

In [63]:
random_tensor = torch.rand(2,4,3)
random_tensor
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([2, 4, 3])


In [64]:
mytensor = torch.rand(size=(1,2))
print(mytensor)

tensor([[0.6981, 0.6639]])


In [65]:
zeros = torch.zeros(3,3,3)
zeros.dtype
ones = torch.ones(2,2,1)
ones

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [66]:
#creating a range of Tensor
torch.arange(1,11)
onetoten = torch.arange(start = 0, end = 10, step = 2)
onetoten

tensor([0, 2, 4, 6, 8])

In [67]:
#creating tensors like
ten_zeros = torch.zeros_like(input =onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0])

#Tensor Datatype
***Note::: Tensor datatypes is one of the 3 big errors in Pytorch
(the other two are: device, shape)

In [68]:
float_32_tensor = torch.tensor([3.0001,6,9],
                               dtype = None,
                               device=None,
                               requires_grad = False)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [69]:
float_32_tensor * float_16_tensor

tensor([ 9.0003, 36.0000, 81.0000])

In [70]:
int_32_tensor = torch.tensor([3.0031,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [71]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8592, 0.1221, 0.8158, 0.7830],
        [0.1342, 0.6268, 0.1775, 0.9452],
        [0.9777, 0.2392, 0.6139, 0.9712]])

In [72]:
print(some_tensor)
print(f'Data type of tensor: {some_tensor.dtype}')
print(f"Size of tensor: {some_tensor.size}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8592, 0.1221, 0.8158, 0.7830],
        [0.1342, 0.6268, 0.1775, 0.9452],
        [0.9777, 0.2392, 0.6139, 0.9712]])
Data type of tensor: torch.float32
Size of tensor: <built-in method size of Tensor object at 0x7a3ced57c230>
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [73]:
#Tensor operations
#include addition, substraction, multiplication(element-wise), division, Matrix multiplication
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 2)
print(tensor -10)
print(torch.mul(tensor,10))
#Check Math is Fun and check Matrix multiplication(dot product)
print(torch.dot(tensor,tensor))
print(torch.matmul(tensor,tensor))
print(tensor @ tensor)
tensor * tensor
# %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor([11, 12, 13])
tensor([2, 4, 6])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)
tensor(14)
tensor(14)
tensor(14)


In [74]:
#Common error is shape error
#Two rules for matrix multiplication
#inner dimensions must match
#result matrix has shape of outer dimensions
print(torch.rand(3,2))
print(torch.rand(2,3))
print(torch.matmul(torch.rand(1,2),torch.rand(2,1)))

tensor([[0.5790, 0.8285],
        [0.4317, 0.2957],
        [0.0998, 0.7108]])
tensor([[0.1810, 0.5863, 0.5741],
        [0.4347, 0.3977, 0.9637]])
tensor([[0.2488]])


In [75]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# transpose to switch axes or dimension of tensor
tensor_B.T, tensor_B.T.shape
torch.mm(tensor_A, tensor_B.T) # same as .matmul
print(f"Original Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.shape}")
print(f"New Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.T.shape}")
print("Output:")
print(torch.mm(tensor_A,tensor_B.T))


Original Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [76]:
#finding min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0,100,10)
print(x.dtype)
torch.max(x),x.min()
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

torch.int64


(tensor(45.), tensor(45.))

In [77]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [78]:
#finding position of min and max
print(x.argmin(),x.argmax())
x[0]


tensor(0) tensor(9)


tensor(0)

In [90]:
#Reshaping , View(same memory as original tensor),Stacking(combine: .stack, .vstack,.hstack)
#Squeeze: remove all '1' dimensions
#Unsqueeze: add a '1' dimension
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [92]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [89]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [99]:
z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [103]:
z[:,0] = 5
z
x

tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])

In [ ]:
#Stacks