<a href="https://colab.research.google.com/github/cpernot/Learn_pytorch/blob/main/00_pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
print ("hello")


hello


In [152]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [153]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.5.1+cu121


In [154]:
## Introduction to Tensors

In [155]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [156]:
scalar.ndim

0

In [157]:
scalar.item()

7

In [158]:
MATRIX = torch.tensor([[1,1],[2,2]])
print(MATRIX.ndim)
print(MATRIX.shape)
TENSOR =torch.tensor([[[1,2,3,4],[2,2,2,2],[3,3,3,3]],
                      [[1,2,3,4],[2,2,2,2],[3,3,3,3]]])
print(TENSOR.ndim)
print(TENSOR.shape)

2
torch.Size([2, 2])
3
torch.Size([2, 3, 4])


###Random Tensors

## #Create a random tensor of size (3,4)

In [159]:
random_tensor = torch.rand(2,4,3)
random_tensor
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([2, 4, 3])


In [160]:
mytensor = torch.rand(size=(1,2))
print(mytensor)

tensor([[0.8978, 0.7661]])


In [161]:
zeros = torch.zeros(3,3,3)
zeros.dtype
ones = torch.ones(2,2,1)
ones

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [162]:
#creating a range of Tensor
torch.arange(1,11)
onetoten = torch.arange(start = 0, end = 10, step = 2)
onetoten

tensor([0, 2, 4, 6, 8])

In [163]:
#creating tensors like
ten_zeros = torch.zeros_like(input =onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0])

#Tensor Datatype
***Note::: Tensor datatypes is one of the 3 big errors in Pytorch
(the other two are: device, shape)

In [164]:
float_32_tensor = torch.tensor([3.0001,6,9],
                               dtype = None,
                               device=None,
                               requires_grad = False)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [165]:
float_32_tensor * float_16_tensor

tensor([ 9.0003, 36.0000, 81.0000])

In [166]:
int_32_tensor = torch.tensor([3.0031,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [167]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8741, 0.8486, 0.1388, 0.9359],
        [0.0206, 0.7414, 0.9362, 0.3516],
        [0.7082, 0.5352, 0.2582, 0.1564]])

In [168]:
print(some_tensor)
print(f'Data type of tensor: {some_tensor.dtype}')
print(f"Size of tensor: {some_tensor.size}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8741, 0.8486, 0.1388, 0.9359],
        [0.0206, 0.7414, 0.9362, 0.3516],
        [0.7082, 0.5352, 0.2582, 0.1564]])
Data type of tensor: torch.float32
Size of tensor: <built-in method size of Tensor object at 0x7a3ced5b67b0>
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [169]:
#Tensor operations
#include addition, substraction, multiplication(element-wise), division, Matrix multiplication
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 2)
print(tensor -10)
print(torch.mul(tensor,10))
#Check Math is Fun and check Matrix multiplication(dot product)
print(torch.dot(tensor,tensor))
print(torch.matmul(tensor,tensor))
print(tensor @ tensor)
tensor * tensor
# %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor([11, 12, 13])
tensor([2, 4, 6])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)
tensor(14)
tensor(14)
tensor(14)


In [170]:
#Common error is shape error
#Two rules for matrix multiplication
#inner dimensions must match
#result matrix has shape of outer dimensions
print(torch.rand(3,2))
print(torch.rand(2,3))
print(torch.matmul(torch.rand(1,2),torch.rand(2,1)))

tensor([[0.3906, 0.2521],
        [0.4354, 0.5442],
        [0.1535, 0.8005]])
tensor([[0.2493, 0.9917, 0.7343],
        [0.8307, 0.7060, 0.1514]])
tensor([[0.3431]])


In [171]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# transpose to switch axes or dimension of tensor
tensor_B.T, tensor_B.T.shape
torch.mm(tensor_A, tensor_B.T) # same as .matmul
print(f"Original Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.shape}")
print(f"New Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.T.shape}")
print("Output:")
print(torch.mm(tensor_A,tensor_B.T))


Original Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [172]:
#finding min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0,100,10)
print(x.dtype)
torch.max(x),x.min()
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

torch.int64


(tensor(45.), tensor(45.))

In [173]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [174]:
#finding position of min and max
print(x.argmin(),x.argmax())
x[0]


tensor(0) tensor(9)


tensor(0)

In [175]:
#Reshaping , View(same memory as original tensor),Stacking(combine: .stack, .vstack,.hstack)
#Squeeze: remove all '1' dimensions
#Unsqueeze: add a '1' dimension
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [176]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [177]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [178]:
z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [179]:
z[:,0] = 5
z
x

tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])

In [180]:
#Stacks
x_stacked = torch.stack([z,z,z],dim=2)
x_stacked

tensor([[[ 5.,  5.,  5.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.]],

        [[ 5.,  5.,  5.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.]]])

In [181]:
#Squeeze
x = torch.zeros(2, 1, 2, 1, 2)
print(f"x size: {x.size()}")
y = torch.squeeze(x)
print(y)
print(f"y size: {y.size()}")
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))


x size: torch.Size([2, 1, 2, 1, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
y size: torch.Size([2, 2, 2])


In [185]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
Previous shape: torch.Size([10, 1])

New Tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
New Shape: torch.Size([10])


In [194]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
Previous shape:torch.Size([10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [196]:
x_original = torch.rand(size=(224,224,3))#height width colours_channels
#permute the original to rearrange the axis
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: { x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [209]:
x_original[0,0,0] =7222
#x_permuted
print(x_original[0,0,0] ,x_permuted[0,0,0] )

tensor(7222.) tensor(7222.)


In [212]:
#Indexing with Pytorch is similar to NumPy
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [218]:
x[0][2]

tensor([7, 8, 9])

In [223]:
x[0][1][2]

tensor(6)

In [238]:
x[:,:,2]

tensor([[3, 6, 9]])