<a href="https://colab.research.google.com/github/cpernot/Learn_pytorch/blob/main/00_pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("hello")


hello


In [2]:
!nvidia-smi

Sat Jan 25 09:23:23 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.5.1+cu121


In [6]:
## Introduction to Tensors

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [14]:
MATRIX = torch.tensor([[1,1],[2,2]])
print(MATRIX.ndim)
print(MATRIX.shape)
TENSOR =torch.tensor([[[1,2,3,4],[2,2,2,2],[3,3,3,3]],
                      [[1,2,3,4],[2,2,2,2],[3,3,3,3]]])
print(TENSOR.ndim)
print(TENSOR.shape)

2
torch.Size([2, 2])
3
torch.Size([2, 3, 4])


###Random Tensors

## #Create a random tensor of size (3,4)

In [20]:
random_tensor = torch.rand(2,4,3)
random_tensor
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([2, 4, 3])


In [23]:
mytensor = torch.rand(size=(1,2))
print(mytensor)

tensor([[0.0639, 0.9181]])


In [27]:
zeros = torch.zeros(3,3,3)
zeros.dtype
ones = torch.ones(2,2,1)
ones

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [32]:
#creating a range of Tensor
torch.arange(1,11)
onetoten = torch.arange(start = 0, end = 10, step = 2)
onetoten

tensor([0, 2, 4, 6, 8])

In [34]:
#creating tensors like
ten_zeros = torch.zeros_like(input =onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0])

#Tensor Datatype
***Note::: Tensor datatypes is one of the 3 big errors in Pytorch
(the other two are: device, shape)

In [53]:
float_32_tensor = torch.tensor([3.0001,6,9],
                               dtype = None,
                               device=None,
                               requires_grad = False)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [56]:
float_32_tensor * float_16_tensor

tensor([ 9.0003, 36.0000, 81.0000])

In [5]:
int_32_tensor = torch.tensor([3.0031,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [6]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3622, 0.0929, 0.0636, 0.1673],
        [0.8105, 0.0514, 0.2820, 0.1283],
        [0.9055, 0.7585, 0.7938, 0.0209]])

In [8]:
print(some_tensor)
print(f'Data type of tensor: {some_tensor.dtype}')
print(f"Size of tensor: {some_tensor.size}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3622, 0.0929, 0.0636, 0.1673],
        [0.8105, 0.0514, 0.2820, 0.1283],
        [0.9055, 0.7585, 0.7938, 0.0209]])
Data type of tensor: torch.float32
Shize of tensor: <built-in method size of Tensor object at 0x7ac69a17d310>
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [21]:
#Tensor operations
#include addition, substraction, multiplication(element-wise), division, Matrix multiplication
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 2)
print(tensor -10)
print(torch.mul(tensor,10))
#Check Math is Fun and check Matrix multiplication(dot product)
print(torch.dot(tensor,tensor))
print(torch.matmul(tensor,tensor))
print(tensor @ tensor)
tensor * tensor
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor([11, 12, 13])
tensor([2, 4, 6])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)
tensor(14)
tensor(14)


UsageError: Line magic function `%%time` not found.


In [27]:
#Common error is shape error
#Two rules for matrix multiplication
#inner dimensions must match
#result matrix has shape of outer dimensions
print(torch.rand(3,2))
print(torch.rand(2,3))
print(torch.matmul(torch.rand(1,2),torch.rand(2,1)))

tensor([[8.9950e-01, 8.5872e-04],
        [8.0480e-01, 3.4187e-01],
        [5.5570e-01, 8.3778e-01]])
tensor([[0.0585, 0.9893, 0.7218],
        [0.4662, 0.0474, 0.9657]])
tensor([[0.5644]])
