<a href="https://colab.research.google.com/github/cpernot/Learn_pytorch/blob/main/00_pytorch_1_ipynb_%E3%81%AE%E3%82%B3%E3%83%94%E3%83%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("hello")


hello


In [2]:
!nvidia-smi

Sun Jan 26 07:00:25 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.5.1+cu121


In [4]:
## Introduction to Tensors

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
MATRIX = torch.tensor([[1,1],[2,2]])
print(MATRIX.ndim)
print(MATRIX.shape)
TENSOR =torch.tensor([[[1,2,3,4],[2,2,2,2],[3,3,3,3]],
                      [[1,2,3,4],[2,2,2,2],[3,3,3,3]]])
print(TENSOR.ndim)
print(TENSOR.shape)

2
torch.Size([2, 2])
3
torch.Size([2, 3, 4])


###Random Tensors

## #Create a random tensor of size (3,4)

In [9]:
random_tensor = torch.rand(2,4,3)
random_tensor
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([2, 4, 3])


In [10]:
mytensor = torch.rand(size=(1,2))
print(mytensor)

tensor([[0.8319, 0.4494]])


In [11]:
zeros = torch.zeros(3,3,3)
zeros.dtype
ones = torch.ones(2,2,1)
ones

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [12]:
#creating a range of Tensor
torch.arange(1,11)
onetoten = torch.arange(start = 0, end = 10, step = 2)
onetoten

tensor([0, 2, 4, 6, 8])

In [13]:
#creating tensors like
ten_zeros = torch.zeros_like(input =onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0])

#Tensor Datatype
***Note::: Tensor datatypes is one of the 3 big errors in Pytorch
(the other two are: device, shape)

In [14]:
float_32_tensor = torch.tensor([3.0001,6,9],
                               dtype = None,
                               device=None,
                               requires_grad = False)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [15]:
float_32_tensor * float_16_tensor

tensor([ 9.0003, 36.0000, 81.0000])

In [16]:
int_32_tensor = torch.tensor([3.0031,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [17]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0144, 0.6739, 0.9827, 0.6316],
        [0.9730, 0.8879, 0.7779, 0.5969],
        [0.7837, 0.2839, 0.5779, 0.5833]])

In [18]:
print(some_tensor)
print(f'Data type of tensor: {some_tensor.dtype}')
print(f"Size of tensor: {some_tensor.size}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0144, 0.6739, 0.9827, 0.6316],
        [0.9730, 0.8879, 0.7779, 0.5969],
        [0.7837, 0.2839, 0.5779, 0.5833]])
Data type of tensor: torch.float32
Size of tensor: <built-in method size of Tensor object at 0x799a23504410>
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [19]:
#Tensor operations
#include addition, substraction, multiplication(element-wise), division, Matrix multiplication
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 2)
print(tensor -10)
print(torch.mul(tensor,10))
#Check Math is Fun and check Matrix multiplication(dot product)
print(torch.dot(tensor,tensor))
print(torch.matmul(tensor,tensor))
print(tensor @ tensor)
tensor * tensor
# %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor([11, 12, 13])
tensor([2, 4, 6])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)
tensor(14)
tensor(14)
tensor(14)


In [20]:
#Common error is shape error
#Two rules for matrix multiplication
#inner dimensions must match
#result matrix has shape of outer dimensions
print(torch.rand(3,2))
print(torch.rand(2,3))
print(torch.matmul(torch.rand(1,2),torch.rand(2,1)))

tensor([[0.4549, 0.2119],
        [0.6164, 0.9948],
        [0.2451, 0.9660]])
tensor([[0.4466, 0.8415, 0.9117],
        [0.7713, 0.6695, 0.6594]])
tensor([[0.0791]])


In [21]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# transpose to switch axes or dimension of tensor
tensor_B.T, tensor_B.T.shape
torch.mm(tensor_A, tensor_B.T) # same as .matmul
print(f"Original Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.shape}")
print(f"New Shapes: Tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.T.shape}")
print("Output:")
print(torch.mm(tensor_A,tensor_B.T))


Original Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: Tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [22]:
#finding min, max, mean, sum, etc (tensor aggregation)
x = torch.arange(0,100,10)
print(x.dtype)
torch.max(x),x.min()
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

torch.int64


(tensor(45.), tensor(45.))

In [23]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [24]:
#finding position of min and max
print(x.argmin(),x.argmax())
x[0]


tensor(0) tensor(9)


tensor(0)

In [25]:
#Reshaping , View(same memory as original tensor),Stacking(combine: .stack, .vstack,.hstack)
#Squeeze: remove all '1' dimensions
#Unsqueeze: add a '1' dimension
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [26]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [27]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [28]:
z = x.view(2,5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [29]:
z[:,0] = 5
z
x

tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])

In [30]:
#Stacks
x_stacked = torch.stack([z,z,z],dim=2)
x_stacked

tensor([[[ 5.,  5.,  5.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.]],

        [[ 5.,  5.,  5.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.]]])

In [31]:
#Squeeze
x = torch.zeros(2, 1, 2, 1, 2)
print(f"x size: {x.size()}")
y = torch.squeeze(x)
print(y)
print(f"y size: {y.size()}")
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))


x size: torch.Size([2, 1, 2, 1, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
y size: torch.Size([2, 2, 2])


In [32]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
Previous shape: torch.Size([10, 1])

New Tensor: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
New Shape: torch.Size([10])


In [33]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.])
Previous shape:torch.Size([10])

New tensor: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 5.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [34]:
x_original = torch.rand(size=(224,224,3))#height width colours_channels
#permute the original to rearrange the axis
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: { x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [35]:
x_original[0,0,0] =7222
#x_permuted
print(x_original[0,0,0] ,x_permuted[0,0,0] )

tensor(7222.) tensor(7222.)


In [36]:
#Indexing with Pytorch is similar to NumPy
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [37]:
x[0][2]

tensor([7, 8, 9])

In [38]:
x[0][1][2]

tensor(6)

In [39]:
x[:,:,2]

tensor([[3, 6, 9]])

In [40]:
#Pytorch tensors & NumPy
#torch.from_numpy(ndarray)
#torch.Tensor.numpy()
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [41]:
tensor.dtype

torch.float64

In [42]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
#Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [44]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [45]:
#Reproducibility (take random out of random)
#random nb -> tensor operations -> update random nb -> again -> again
torch.rand(3,3)
# to reduce randomness use random seed: it is flavour the randomness

tensor([[0.0956, 0.8805, 0.6586],
        [0.3981, 0.6300, 0.1375],
        [0.5684, 0.9808, 0.1243]])

In [46]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2575, 0.8281, 0.8956, 0.9193],
        [0.8933, 0.9093, 0.2534, 0.3815],
        [0.5271, 0.8657, 0.9182, 0.7213]])
tensor([[0.2020, 0.9582, 0.5889, 0.8137],
        [0.5603, 0.4999, 0.6414, 0.9831],
        [0.0368, 0.6878, 0.6217, 0.4130]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [47]:
#random but reproducible
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


extra resources:
https://pytorch.org/docs/stable/notes/randomness.html

In [48]:
# Running tensors and Pytorch objects on the GPUs(faster computation thanks to CUDA +NVIDIA hardware)
!nvidia-smi

Sun Jan 26 07:00:35 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [49]:
torch.cuda.is_available()

True

In [55]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [51]:
torch.cuda.device_count()

1

In [52]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [56]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [60]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [61]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy
tensor_back_on_cpu()

array([1, 2, 3])